Repository RLinf/RLinf, pull requests merged in 2025-09, with the labels that each got.

#71 feat(placement): add flexible placement
  docs/README.md
  docs/autobuild.sh
  docs/source-en/_static/favicon.ico
  docs/source-en/rst_source/apis/actor.rst
  docs/source-en/rst_source/apis/cluster.rst
  docs/source-en/rst_source/apis/data.rst
  docs/source-en/rst_source/apis/env.rst
  docs/source-en/rst_source/apis/placement.rst
  docs/source-en/rst_source/apis/rollout.rst
  docs/source-en/rst_source/apis/worker.rst
  docs/source-en/rst_source/tutorials/user/placement.rst
  docs/source-en/rst_source/tutorials/user/yaml.rst
  docs/source-zh/_static/favicon.ico
  docs/source-zh/rst_source/apis/actor.rst
  docs/source-zh/rst_source/apis/cluster.rst
  docs/source-zh/rst_source/apis/data.rst
  docs/source-zh/rst_source/apis/env.rst
  docs/source-zh/rst_source/apis/placement.rst
  docs/source-zh/rst_source/apis/rollout.rst
  docs/source-zh/rst_source/apis/worker.rst
  docs/source-zh/rst_source/tutorials/user/placement.rst
  docs/source-zh/rst_source/tutorials/user/yaml.rst
  rlinf/scheduler/__init__.py
  rlinf/scheduler/placement/__init__.py
  rlinf/scheduler/placement/flexible.py
  rlinf/utils/placement.py
  tests/unit_tests/test_placement.py
Labels: enhancement

#54 feat: add mg2hf model convertor
  docs/source-en/rst_source/start/llm-eval.rst
  docs/source-zh/rst_source/start/llm-eval.rst
Labels: enhancement

#137 docs(example-gallery): update example gallery doc pages
  README.md
  docs/source-en/rst_source/examples/index.rst
  docs/source-en/rst_source/examples/libero.rst
  docs/source-en/rst_source/examples/maniskill.rst
  docs/source-en/rst_source/examples/reasoning.rst
  docs/source-zh/rst_source/examples/index.rst
  docs/source-zh/rst_source/examples/libero.rst
  docs/source-zh/rst_source/examples/maniskill.rst
  docs/source-zh/rst_source/examples/reasoning.rst
Labels: documentation

#145 fix: default gloo group due to prismatic import & dep enhancement
  docker/embodied/Dockerfile.openvla.hf.fsdp
  docker/embodied/Dockerfile.openvlaoft.hf.fsdp
  docker/embodied/Dockerfile.pi0.hf.fsdp
  docs/source-en/rst_source/start/installation.rst
  docs/source-zh/rst_source/start/installation.rst
  pyproject.toml
  requirements/README.md
  requirements/install_embodied_deps.sh
  rlinf/hybrid_engines/fsdp/utils.py
  rlinf/workers/rollout/sglang/__init__.py
Labels: bug
